### ISSUE TITLE
input_shape

### ISSUE THREAD

**Issue by skjerns** [JihongJu/keras-resnet3d#1] opened 2017-06-13 14:00 UTC
Hey, 

I realized that only certain `input_shapes` seem to be working or I get a broadcast error.
`Operands could not be broadcast together with shapes`

Do you know how I can easily fix this?
I am working with `(19,19,19)` cubes atm
These are the input_shapes that seem to be allowed:
```
(1,1,1) : ok
(2,2,2) : ok
(3,3,3) : ok
(4,4,4) : ok
(5,5,5) : ok
(6,6,6) : ok
(7,7,7) : ok
(8,8,8) : ok
(9,9,9) : Operands could not be broadcast together with shapes (3, 3, 3, 128) (2, 2, 2, 128)
(10,10,10) : Operands could not be broadcast together with shapes (3, 3, 3, 128) (2, 2, 2, 128)
(11,11,11) : Operands could not be broadcast together with shapes (3, 3, 3, 128) (2, 2, 2, 128)
12 : Operands could not be broadcast together with shapes (3, 3, 3, 512) (2, 2, 2, 512)
13 : ok
14 : ok
15 : ok
16 : ok
17 : Operands could not be broadcast together with shapes (5, 5, 5, 512) (3, 3, 3, 512)
18 : Operands could not be broadcast together with shapes (5, 5, 5, 512) (3, 3, 3, 512)
19 : Operands could not be broadcast together with shapes (5, 5, 5, 512) (3, 3, 3, 512)
20 : Operands could not be broadcast together with shapes (5, 5, 5, 512) (3, 3, 3, 512)
21 : Operands could not be broadcast together with shapes (3, 3, 3, 1024) (2, 2, 2, 1024)
22 : Operands could not be broadcast together with shapes (3, 3, 3, 1024) (2, 2, 2, 1024)
23 : Operands could not be broadcast together with shapes (3, 3, 3, 1024) (2, 2, 2, 1024)
24 : Operands could not be broadcast together with shapes (3, 3, 3, 1024) (2, 2, 2, 1024)
25 : Operands could not be broadcast together with shapes (7, 7, 7, 512) (4, 4, 4, 512)
26 : Operands could not be broadcast together with shapes (7, 7, 7, 512) (4, 4, 4, 512)
27 : Operands could not be broadcast together with shapes (7, 7, 7, 512) (4, 4, 4, 512)
28 : Operands could not be broadcast together with shapes (7, 7, 7, 512) (4, 4, 4, 512)
29 : ok
30 : ok
31 : ok
32 : ok
33 : Operands could not be broadcast together with shapes (9, 9, 9, 512) (5, 5, 5, 512)
34 : Operands could not be broadcast together with shapes (9, 9, 9, 512) (5, 5, 5, 512)
35 : Operands could not be broadcast together with shapes (9, 9, 9, 512) (5, 5, 5, 512)
36 : Operands could not be broadcast together with shapes (9, 9, 9, 512) (5, 5, 5, 512)
37 : Operands could not be broadcast together with shapes (5, 5, 5, 1024) (3, 3, 3, 1024)
38 : Operands could not be broadcast together with shapes (5, 5, 5, 1024) (3, 3, 3, 1024)
39 : Operands could not be broadcast together with shapes (5, 5, 5, 1024) (3, 3, 3, 1024)
40 : Operands could not be broadcast together with shapes (5, 5, 5, 1024) (3, 3, 3, 1024)
41 : Operands could not be broadcast together with shapes (11, 11, 11, 512) (6, 6, 6, 512)
42 : Operands could not be broadcast together with shapes (11, 11, 11, 512) (6, 6, 6, 512)
43 : Operands could not be broadcast together with shapes (11, 11, 11, 512) (6, 6, 6, 512)
44 : Operands could not be broadcast together with shapes (11, 11, 11, 512) (6, 6, 6, 512)
45 : Operands could not be broadcast together with shapes (3, 3, 3, 2048) (2, 2, 2, 2048)
46 : Operands could not be broadcast together with shapes (3, 3, 3, 2048) (2, 2, 2, 2048)
47 : Operands could not be broadcast together with shapes (3, 3, 3, 2048) (2, 2, 2, 2048)
48 : Operands could not be broadcast together with shapes (3, 3, 3, 2048) (2, 2, 2, 2048)
49 : Operands could not be broadcast together with shapes (13, 13, 13, 512) (7, 7, 7, 512)
50 : Operands could not be broadcast together with shapes (13, 13, 13, 512) (7, 7, 7, 512)
51 : Operands could not be broadcast together with shapes (13, 13, 13, 512) (7, 7, 7, 512)
52 : Operands could not be broadcast together with shapes (13, 13, 13, 512) (7, 7, 7, 512)
53 : Operands could not be broadcast together with shapes (7, 7, 7, 1024) (4, 4, 4, 1024)
54 : Operands could not be broadcast together with shapes (7, 7, 7, 1024) (4, 4, 4, 1024)
55 : Operands could not be broadcast together with shapes (7, 7, 7, 1024) (4, 4, 4, 1024)
56 : Operands could not be broadcast together with shapes (7, 7, 7, 1024) (4, 4, 4, 1024)
57 : Operands could not be broadcast together with shapes (15, 15, 15, 512) (8, 8, 8, 512)
58 : Operands could not be broadcast together with shapes (15, 15, 15, 512) (8, 8, 8, 512)
59 : Operands could not be broadcast together with shapes (15, 15, 15, 512) (8, 8, 8, 512)
60 : Operands could not be broadcast together with shapes (15, 15, 15, 512) (8, 8, 8, 512)
61 : ok
62 : ok
63 : ok
64 : ok
65 : Operands could not be broadcast together with shapes (17, 17, 17, 512) (9, 9, 9, 512)
66 : Operands could not be broadcast together with shapes (17, 17, 17, 512) (9, 9, 9, 512)
67 : Operands could not be broadcast together with shapes (17, 17, 17, 512) (9, 9, 9, 512)
68 : Operands could not be broadcast together with shapes (17, 17, 17, 512) (9, 9, 9, 512)
69 : Operands could not be broadcast together with shapes (9, 9, 9, 1024) (5, 5, 5, 1024)
70 : Operands could not be broadcast together with shapes (9, 9, 9, 1024) (5, 5, 5, 1024)
71 : Operands could not be broadcast together with shapes (9, 9, 9, 1024) (5, 5, 5, 1024)
72 : Operands could not be broadcast together with shapes (9, 9, 9, 1024) (5, 5, 5, 1024)
73 : Operands could not be broadcast together with shapes (19, 19, 19, 512) (10, 10, 10, 512)
74 : Operands could not be broadcast together with shapes (19, 19, 19, 512) (10, 10, 10, 512)
75 : Operands could not be broadcast together with shapes (19, 19, 19, 512) (10, 10, 10, 512)
76 : Operands could not be broadcast together with shapes (19, 19, 19, 512) (10, 10, 10, 512)
77 : Operands could not be broadcast together with shapes (5, 5, 5, 2048) (3, 3, 3, 2048)
78 : Operands could not be broadcast together with shapes (5, 5, 5, 2048) (3, 3, 3, 2048)
79 : Operands could not be broadcast together with shapes (5, 5, 5, 2048) (3, 3, 3, 2048)
80 : Operands could not be broadcast together with shapes (5, 5, 5, 2048) (3, 3, 3, 2048)
81 : Operands could not be broadcast together with shapes (21, 21, 21, 512) (11, 11, 11, 512)
82 : Operands could not be broadcast together with shapes (21, 21, 21, 512) (11, 11, 11, 512)
83 : Operands could not be broadcast together with shapes (21, 21, 21, 512) (11, 11, 11, 512)
84 : Operands could not be broadcast together with shapes (21, 21, 21, 512) (11, 11, 11, 512)
85 : Operands could not be broadcast together with shapes (11, 11, 11, 1024) (6, 6, 6, 1024)
86 : Operands could not be broadcast together with shapes (11, 11, 11, 1024) (6, 6, 6, 1024)
87 : Operands could not be broadcast together with shapes (11, 11, 11, 1024) (6, 6, 6, 1024)
88 : Operands could not be broadcast together with shapes (11, 11, 11, 1024) (6, 6, 6, 1024)
89 : Operands could not be broadcast together with shapes (23, 23, 23, 512) (12, 12, 12, 512)
90 : Operands could not be broadcast together with shapes (23, 23, 23, 512) (12, 12, 12, 512)
91 : Operands could not be broadcast together with shapes (23, 23, 23, 512) (12, 12, 12, 512)
92 : Operands could not be broadcast together with shapes (23, 23, 23, 512) (12, 12, 12, 512)
93 : ok
94 : ok
95 : ok
96 : ok
97 : Operands could not be broadcast together with shapes (25, 25, 25, 512) (13, 13, 13, 512)
98 : Operands could not be broadcast together with shapes (25, 25, 25, 512) (13, 13, 13, 512)
99 : Operands could not be broadcast together with shapes (25, 25, 25, 512) (13, 13, 13, 512)
```

**Comment by JihongJu** [comment] 2017-06-13 19:35
Thanks @skjerns! What you have is SUPER useful. This is a known bug caused by the shortcut. What I have in mind is to solve this is to replace the crop layers that not match but that may cause unalignment problems. Maybe you have ideas on this?

**Comment by banco2** [comment] 2017-10-26 16:54
Hi, @JihongJu, were you able to fix this bug? i tried it on 112x112 input and was also Operands could not be broadcast together with shapes error. Thank you.

**Comment by mkompanek** [comment] 2018-11-09 15:16
Hi, I fixed the problem by changing shortcut function:
```
def _shortcut3d(input, residual):
    """3D shortcut to match input and residual and merges them with "sum"."""    
    stride_dim1 = int((input._keras_shape[DIM1_AXIS] / residual._keras_shape[DIM1_AXIS])+0.5)
    stride_dim2 = int((input._keras_shape[DIM2_AXIS] / residual._keras_shape[DIM2_AXIS])+0.5)
    stride_dim3 = int((input._keras_shape[DIM3_AXIS] / residual._keras_shape[DIM3_AXIS])+0.5)    
    equal_channels = residual._keras_shape[CHANNEL_AXIS] == input._keras_shape[CHANNEL_AXIS]

    shortcut = input
    if stride_dim1 > 1 or stride_dim2 > 1 or stride_dim3 > 1 \
            or not equal_channels:
        shortcut = Conv3D(
            filters=residual._keras_shape[CHANNEL_AXIS],
            kernel_size=(1, 1, 1),
            strides=(stride_dim1, stride_dim2, stride_dim3),
            kernel_initializer="he_normal", padding="valid",
            kernel_regularizer=l2(1e-4)
            )(input)
    
    return add([shortcut, residual])

```

**Comment by shijianjian** [comment] 2019-01-02 03:22
Thank @mkompanek for the fix
While I think use **math.ceil** makes more sense than add 0.5 here.
```python
from math import ceil

stride_dim1 = ceil((input._keras_shape[DIM1_AXIS] / residual._keras_shape[DIM1_AXIS]))
stride_dim2 = ceil((input._keras_shape[DIM2_AXIS] / residual._keras_shape[DIM2_AXIS]))
stride_dim3 = ceil((input._keras_shape[DIM3_AXIS] / residual._keras_shape[DIM3_AXIS]))
```

**Comment by abdullahshafin** [comment] 2019-03-19 16:38
@mkompanek @shijianjian I came here to open an issue regarding this and to suggest a fix, didn't know there was already an open issue. Should have checked it first and I would've saved a few hours figuring it out myself. 

I don't know what's the best solution but I came up with round() function from python for the fix after looking at the divison values that came up. I thought this would make more sense than math.ceil() since if the division give 2.14 after divison, I would want it to be using factor 2 and not 3. However, I am not sure if it happens in practice. Anyway, my fix worked fine for me for an input shape (None, 264, 264, 219).

@JihongJu it would be great if you can add this fix. Your code would've worked absolutely seamlessly if I had not encountered this issue. I am sure it will help a lot more people and will lead to more adoption of your implementation. If I can help with this, just let me know.

```python
def _shortcut3d(input, residual):
    """3D shortcut to match input and residual and merges them with "sum"."""
    stride_dim1 = round(input._keras_shape[DIM1_AXIS]/residual._keras_shape[DIM1_AXIS])
    stride_dim2 = round(input._keras_shape[DIM2_AXIS]/residual._keras_shape[DIM2_AXIS])
    stride_dim3 = round(input._keras_shape[DIM3_AXIS]/residual._keras_shape[DIM3_AXIS])
```

**Comment by JihongJu** [comment] 2019-09-28 08:47
Hi all, thank you for being interested in the project. Unfortunately, I am not able to actively maintain it. Sorry about that.

The pull request #1 has been merged. Again thank you all for being very helpful.

**Closed as completed** 2019-09-28 08:47 UTC
Labels: enhancement, help wanted
